language: python

services:
  - docker

before_script:
  = docker build -t champop-classifier:dev -f Dockerfile-dev .
# command to install dependencies
script: docker run -it -v $(PWD):/app $(CONTAINER_NAME):dev pytest
branches:
  only:
    - master
