language: python

services:
  - docker

before_install:
  - docker build -t champop-classifier:dev -f Dockerfile-dev .
  - docker run -it champop-classifier:dev /bin/sh -c "pytest"

# command to install dependencies
script: pytest

