name: champop-classifier-gpu
dependencies:
  - matplotlib
  - pillow
  - numpy
  - pandas
  - tensorflow-gpu=1.13.1
  - keras
  - imageio
  - imgaug
  - pip
  - pip:
    - opencv-python
    - mrcnn
    - pickle-mixin
