FROM python:3.6.8-slim as base

ENV FLASK_APP=classifier
ENV FLASK_ENV=development

WORKDIR /app

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD [ "flask", "run", "--host", "0.0.0.0" ]
