FROM python:3.6.8-slim as base

WORKDIR /app

RUN pip install pytest-cov pytest codecov

COPY requirements.txt /tmp
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt

RUN COPY . .

ENV FLASK_APP=champop-classifier
ENV FLASK_ENV=development

EXPOSE 5000

CMD [ "flask", "run", "--host", "0.0.0.0" ]
